### ISSUE TITLE
Python 3.12 Compatibility

### ISSUE THREAD

**Issue by santaimpersonator** [backstage/mkdocs-monorepo-plugin#117]
Unfortunately, the [newly released Python 3.12 removed `distutils`](https://docs.python.org/3/whatsnew/3.12.html) after it being deprecated since since Python 3.10.

* See [PEP 632 Deprecate `distutils` module](https://peps.python.org/pep-0632/) and [gh-92584](https://github.com/python/cpython/issues/92584) for more details about its removal.

With Python 3.12, the use of `distutils` in [merger.py](https://github.com/backstage/mkdocs-monorepo-plugin/blob/master/mkdocs_monorepo_plugin/merger.py#L16) creates an error:

 ```
 File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/mkdocs_monorepo_plugin/merger.py", line 16, in <module>
    from distutils.dir_util import copy_tree
ModuleNotFoundError: No module named 'distutils'
```

We found that including the [`setuptools` module](https://pypi.org/project/setuptools/), which now includes `distutils` to be a simple workaround for the issue.

**Comment by bih** [comment]
This is fixed in #120. Closing.
