### ISSUE TITLE
The github pages link for this repo results in a 404

### ISSUE THREAD

**Issue by stevemar** [backstage/mkdocs-monorepo-plugin#33]
It seems like the mkdocs-monorepo-plugin repo has moved from https://github.com/spotify/mkdocs-monorepo-plugin to https://github.com/backstage/mkdocs-monorepo-plugin and as such the github pages link it now broken and results in a 404.

It's a known issue that when a repo is transferred between organizations and users the github repos automatically redirect but the github pages do not.

Please update the old link (https://spotify.github.io/mkdocs-monorepo-plugin/) to the new link (https://backstage.github.io/mkdocs-monorepo-plugin/)

**Comment by OrkoHunter** [comment]
Thanks a lot for reporting @stevemar ! Updated the repo description link.

**Comment by stevemar** [comment]
No problem 👍
