### ISSUE TITLE
docs_dir from included mkdocs.yml

### ISSUE THREAD

**Issue by haneul** [backstage/mkdocs-monorepo-plugin#41]
https://backstage.github.io/mkdocs-monorepo-plugin/limitations/ lists this as know limitation
* In an included mkdocs.yml, it currently looks for the relative docs/ folder and does not respect the docs_dir value.

Any plans to change this? sometimes it doesn't make much sense to create docs directory separately when some directory already has documents.

**Comment by Fox32** [comment]
Duplicate of #40?

**Comment by iamEAP** [comment]
Thanks for triaging @Fox32!  @haneul, would you mind adding your use-case in #40?  We can continue the conversation there.

**Comment by haneul** [comment]
sure I'll add there. I thought the use case was slightly different but may still fall into the same issue.
