### ISSUE TITLE
Warnings during build ("duplicate filename")

### ISSUE THREAD

**Issue by FredrikMeyer** [backstage/mkdocs-monorepo-plugin#50]
Thanks for the great plugin!

This is maybe just a question, not an issue, but here goes:

We have a lot of "sub-documentations", and during build of the root `mkdocs.yml`, we get a lot of warnings during build:

```
WARNING -  Duplicate filename: 'protocol.md' exists at both '/var/folders/s5/d5n7fmn927q89ky03v4tbz_00000gn/T/docs_vokpwu1o/something/protocol.md' and '/var/folders/s5/d5n7fmn927q89ky03v4tbz_00000gn/T/docs_vokpwu1o/something/protocol.md'
WARNING -  Duplicate filename: 'engine.md' exists at both '/var/folders/s5/d5n7fmn927q89ky03v4tbz_00000gn/T/docs_vokpwu1o/xx/engine.md' and '/var/folders/s5/d5n7fmn927q89ky03v4tbz_00000gn/T/docs_vokpwu1o/xx/engine.md'
```

Is this a known thing, or do we maybe have a configuration error? I cannot see what is immediately wrong about reusing a file name as long as they are in different directories.

**Comment by camilaibs** [comment]
Hi @FredrikMeyer thanks for opening the issue, is it still happening for you?
I tried to simulate in [simple-docs](https://github.com/backstage/mkdocs-monorepo-plugin/tree/master/sample-docs) folder that we have at the root of the project and I couldn't see this warning.

Version:
- mkdocs 1.2.3 (Python 3.9)

Command: 
```sh
cd simple-docs
mkdocs build -v
```

Folder structure:
```sh
.
├── docs
│   ├── authentication.md
│   └── index.md
├── mkdocs.yml
├── v1
│   ├── docs
│   │   ├── changelog.md
│   │   └── reference.md
│   └── mkdocs.yml
├── v2
│   ├── docs
│   │   ├── changelog.md
│   │   ├── migrating.md
│   │   └── reference.md
│   └── mkdocs.yml
└── v3
    ├── docs
    │   ├── changelog.md
    │   ├── migrating.md
    │   └── reference.md
    └── mkdocs.yml
```

**Comment by FredrikMeyer** [comment]
Thanks for your answer!

I tried checking out the repo and trying the minimal example, and I don't see them either.

So I did some digging, and it turns out that the warnings came from another plugin (the autolinks plugin, https://github.com/midnightprioriem/mkdocs-autolinks-plugin). (which I just removed from our project since we weren't using it)

Sorry for the issue!

**Comment by camilaibs** [comment]
Thanks for the quick response, I'll close the issue 🙂
