### ISSUE TITLE
Allow for spaces in site_name of sub-docs

### ISSUE THREAD

**Issue by jaklan** [backstage/mkdocs-monorepo-plugin#56]
Hi, currently the plugin fails if any of sub-projects' site name include whitespaces. The assumption is to use that name just to generate an URL, because we show the root site name anyway, so whitespaces seem redundant. However:
-  when you move some repository to monorepo - you need to remember to edit the site_name, because it would fail otherwise
-  if you want to generate a mkdocs site just for given sub-project (e.g. you work on a sub-project workspace in VS Code) - you get an ugly site title with dashes / underscores / slashes

Imho it can be fixed easily - instead of forbidding whitespaces, let's just replace them with underscores automatically by plugin when reading the config values. This way we don't introduce any breaking changes and we make the transition to monorepo even easier 😉 

```
❯ mkdocs serve
INFO     -  Building documentation...
[mkdocs-monorepo] Site name can only contain letters, numbers, underscores, hyphens and forward-slashes. The regular expression we test against is '^[a-zA-Z0-9_\-/]+$'.
```

**Comment by fmg-dave** [comment]
+1

I would also like this feature.
