### ISSUE TITLE
Is additional configuration required in order to use Git Submodules?

### ISSUE THREAD

**Issue by carlreid** [backstage/mkdocs-monorepo-plugin#89]
I have a situation where I am able to execute `python -m mkdocs serve` and have a monorepo documentation site run with no problem (even with a fresh clone).

However, when it comes to execution in backstage, I get something like:
`[mkdocs-monorepo] The file path /tmp/backstage-0tvdBh/my-other-repo-submodule/mkdocs.yml does not exist, is not valid YAML, or does not contain a valid 'site_name' and 'nav' keys.`

My guess right now is that the clone of the repository isn't including `--recurse-submodules` and therefor has no content, but I am also unsure on where I should look for this or enable this. Do I have to modify something else in backstage to properly support Git Submodules?

**Comment by carlreid** [comment]
I agree and I don't believe it is responsible, but I had no idea where else to try ask/look. As far as I am aware it "should just work" if you read the documentation here in the README, as it states no other requirements anywhere.

**Comment by whiskeysierra** [comment]
Git submodules are a very different beast. My advice is to avoid them completely.
