### ISSUE TITLE
Status of the Project

### ISSUE THREAD

**Issue by jgarte** [backstage/mkdocs-monorepo-plugin#96]
Hi,

What is the status of this project? Is it still being actively maintained?

**Comment by mpreisler** [comment]
+1

Could we please get a release containing https://github.com/backstage/mkdocs-monorepo-plugin/pull/86 ? Otherwise we can't use this with mkdocs 1.4.0 and newer.

**Comment by franciscaGrandon** [comment]
I think https://github.com/backstage/mkdocs-monorepo-plugin/pull/86 was merged, and closed the issue, but I haven't tested if its working, has anybody?

**Comment by bih** [comment]
There is a new `1.1.0` release which includes the fix mentioned in #86 and adds support for Python 3.12. In regards to being maintained, yes it is :)

**Comment by bih** [comment]
Closing as this is now fixed.
